version: '3.7'

services:
  mongo:
    ports:
      - 27017:27017

  api:
    volumes:
      - ./api:/opt/code
    ports:
      - 5000

  worker:
    volumes:
      - ./api:/opt/code

  mongo-express:
    ports:
      - 8081:8081

  worker_monitor:
    ports:
      - 5555:5555
