version: '3.7'

volumes:
  mgo-data:
    driver: local
  mgo-config:
    driver: local

services:
  mongo:
    image: mongo:5.0.8-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mgo-data:/data/db
      - mgo-config:/data/configdb

  redis:
    image: redis:alpine

  api: 
    image: neosapience/appname-api:dev
    env_file: 
      - api.env
    depends_on:
      - mongo
      - redis

  worker:
    image: neosapience/appname-api:dev
    command: celery -A task worker
    env_file: 
      - api.env
    depends_on:
      - redis

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  worker_monitor:
    image: neosapience/appname-api:dev
    command: "celery -A task flower"
    env_file: 
      - api.env
